### ISSUE TITLE
Error with oc replace

### ISSUE THREAD

**Issue by strangiato** [RedHatQuickCourses/rhods-admin#25]
@jramcast 

The instructions recommend doing an `oc replace` when applying the oauth object here:

https://github.com/RedHatQuickCourses/rhods-admin/blob/10e64f065b2a322e5357a75a44235200f8050de1/modules/ROOT/pages/index.adoc?plain=1#L65

When attempting to follow those instructions it throws the following error:

```
oc replace -f auth.yaml                                                
oauth.config.openshift.io/cluster replaced
clusterrolebinding.rbac.authorization.k8s.io/cluster-admin-admin replaced
Error from server (NotFound): error when replacing "auth.yaml": secrets "htpasswd" not found
```

**Comment by jramcast** [comment]
`oc apply` might be a better approach in this case, I guess?

**Comment by rsriniva** [comment]
@strangiato - did this work. can we close this out? any helpful tips for associates to be added to text?

**Comment by rsriniva** [comment]
@jramcast  @strangiato - I am not sure this is the 100% correct fix for this. Are we missing extra commands to prep the htpasswd file? Should we just link to the OCP product docs on how to create an admin user plus five normal users?

**Comment by rsriniva** [comment]
@jhurlock @jhurlocker - FYI.

**Comment by rsriniva** [comment]
Did you actually test this in a cluster @jramcast - I am thinking of removing this and just re-directing users to product docs

**Comment by jramcast** [comment]
No, I haven't tested. That's the solution someone mentioned in one of the workshops IIRC.

**Comment by rsriniva** [comment]
ok. I tested this. Thank you @jramcast for the solution. Had to split the auth and secret into separate files
