### ISSUE TITLE
NVIDIA GPU Operator Wrong Name

### ISSUE THREAD

**Issue by linuxeroagrio** [RedHatQuickCourses/rhods-admin#32]
The name of the operator at the TIP section for install vía YAML or GitOps is wrong for NVIDIA GPU Operator. The actual value is "**Node Feature Discovery Operator** " when it should be "**NVIDIA GPU Operator**". See the image bellow.

![wrong-name-nvidia-ope](https://github.com/RedHatQuickCourses/rhods-admin/assets/71896236/cf9afede-acc8-4858-9ff9-578b14492489)

**Comment by rsriniva** [comment]
@jramcast - any idea about this one? cut and paste error?

**Comment by jramcast** [comment]
Yeah, copy&paste error, just change it to `NVIDIA GPU Operator`

**Comment by rsriniva** [comment]
PR to fix this issue- #38
