### ISSUE TITLE
unclear reference in exercise

### ISSUE THREAD

**Issue by raffaelespazzoli** [RedHatQuickCourses/rhods-admin#34]
it's unclear what this `/6.rhod-admin/custom-images.` is referring to. You can find it here: https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter3/custom.html#:~:text=txt%20file%20under-,/6.rhod%2Dadmin/custom%2Dimages.,-The%20only%20package

**Comment by rsriniva** [comment]
@raffaelespazzoli - it's this file https://github.com/RedHatQuickCourses/rhods-qc-apps/blob/main/6.rhod-admin/custom-images/requirements.txt. 

@jramcast - something is missing in this lab. Are we missing instructions to clone the rhods-qc-apps repo here?

**Comment by jramcast** [comment]
Good catch @raffaelespazzoli . Yes, we should add steps for students to make it clear that we want them to clone the `rhods-qc-apps` repo to their workstation.
Something like this:


1. Clone the https://github.com/RedHatQuickCourses/rhods-qc-apps repository to your workstation.
2. Navigate to the cloned repository, and open the `requirements.txt` file under `6.rhod-admin/custom-images`.
3. ...

**Comment by rsriniva** [comment]
> Good catch @raffaelespazzoli . Yes, we should add steps for students to make it clear that we want them to clone the `rhods-qc-apps` repo to their workstation. Something like this:
> 
> 1. Clone the https://github.com/RedHatQuickCourses/rhods-qc-apps repository to your workstation.
> 2. Navigate to the cloned repository, and open the `requirements.txt` file under `6.rhod-admin/custom-images`.
> 3. ...

Should we be cloning the repo on workstation using git cli or clone it in RHOAI Workbench Notebook?

**Comment by jramcast** [comment]
> > Good catch @raffaelespazzoli . Yes, we should add steps for students to make it clear that we want them to clone the `rhods-qc-apps` repo to their workstation. Something like this:
> > 
> > 1. Clone the https://github.com/RedHatQuickCourses/rhods-qc-apps repository to your workstation.
> > 2. Navigate to the cloned repository, and open the `requirements.txt` file under `6.rhod-admin/custom-images`.
> > 3. ...
> 
> Should we be cloning the repo on workstation using git cli or clone it in RHOAI Workbench Notebook?

It's important they clone the code in their laptop/workstation, cause in this exercise they must use `podman build` to generate a container image. They can't do that in a workbench.

**Comment by rsriniva** [comment]
fixed in main. added instructions to git clone apps repo before building custom image
