### ISSUE TITLE
User Count field and Salesforce ID

### ISSUE THREAD

**Issue by viniciusfcf** [RedHatQuickCourses/rhods-admin#35]
Salesforce ID can't be blank when requesting more than 1 user. RHDP message: "User count greater than one requires a valid SalesForceID."

Page: https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/index.html

**Comment by rsriniva** [comment]
can you check again @viniciusfcf - this worked me for me - did you select Practice/Enablement for the Activity field, and Learning about the product for the Purpose fields?

**Comment by rsriniva** [comment]
The RHDP infra is now a mix of AWS + OSP/OCP Virt/IBM cloud, so the first choice "Red Hat OpenShift Container Platform 4.13 Workshop" should work

**Comment by rsriniva** [comment]
@viniciusfcf confirms that he cannot create > 1 user. Maybe we need to amend our instructions to ask folks to open tickets with RHDP team about increasing the count with the added warning that their location codes will be billed for consumption?

@strangiato @jramcast - did we get a special access to > 1 user for the workshop? 

@stencell - we may need to talk to Sha/RHDP team about classrooms for this course? I don't understand why adding users to OCP needs to be charged?

**Comment by stencell** [comment]
@rsriniva Please open a ticket with them and get to the bottom of this. I also provisioned according to the instructions and it worked for me. I don't think I have any special permissions, just a regular user.

**Comment by rsriniva** [comment]
@viniciusfcf - can you please re-create catalog item with 5 users, but this time in salesforce ID field, just type some random string comment as commented by others above. See if this works.

**Comment by viniciusfcf** [comment]
@rsriniva the "RHOAI Munich Workshop" as Salesforce ID worked well.

**Comment by viniciusfcf** [comment]
Sure. Any random string in the field enable the "Order" button. I tested with "Learning RHOAI" and the environment status is "provising"

**Comment by rsriniva** [comment]
Thank you. Will update the instructions soon.

**Comment by rsriniva** [comment]
@jramcast @viniciusfcf - PR for fix https://github.com/RedHatQuickCourses/rhods-admin/pull/36
