### ISSUE TITLE
Suggest installation of RHOAI v2.4 of operator to ensure labs work as developed and tested 

### ISSUE THREAD

**Issue by rsriniva** [RedHatQuickCourses/rhods-admin#37]
Several labs down the LP (Deployment course) have issues if the latest v2.5 of the RHOAI operator is installed. 

In the installation section, recommend users to install v2.4 of the operator

**Comment by jramcast** [comment]
The URLs of all quick courses include a version id (1.33) - e.g. https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/index.html

We might want to update the product version at https://github.com/RedHatQuickCourses/rhods-admin/blob/main/antora.yml#L3 , ideally for all courses.

Also, in the home page of each course, we should clarify that the course targets version 2.4 of RHOAI.

**Comment by rsriniva** [comment]
@jramcast @jtesar-rh - The latest operator does not allow us to choose older versions. Essentially RHOAI has become a rolling release:-). I will close this issue and open a new one to retake all screenshots for the new operator
