### ISSUE TITLE
Update Operator Name From Red Hat OpenShift Data Science to  Red Hat OpenShift AI

### ISSUE THREAD

**Issue by cbowland** [RedHatQuickCourses/rhods-admin#40]
On this page, the instructions say to 

"Navigate to Operators → OperatorHub and search for Red Hat OpenShift Data Science."

I think the name has changed and the instructions should change to

Navigate to Operators → OperatorHub and search for  Red Hat OpenShift AI.

**Comment by rsriniva** [comment]
Noted. We need to retake the screenshots and update the instructions for the new operator. Thanks for reporting this @cbowland
