### ISSUE TITLE
Links to https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-admin#48]
The page https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/index.html links to

- [Product Documentation for Red Hat OpenShift AI](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1)
- [Product Documentation for Red Hat OpenShift AI self-managed](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed)

Both links point to (under) https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science and https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed which causes an immediate redirect to

- https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_cloud_service/1
- https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.8

It'd be good to point directly to the ultimate target location under https://access.redhat.com/documentation/en-us/red_hat_openshift_ai*, stop relying on the redirect on access.redhat.com.

**Comment by rsriniva** [comment]
fixed in main
