### ISSUE TITLE
Node Feature Discovery Operator link points to old documentation version

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-admin#49]
The page https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/install-general-info.html says

> [Node Feature Discovery Operator](https://docs.openshift.com/container-platform/4.13/hardware_enablement/psap-node-feature-discovery-operator.html)

with a link to https://docs.openshift.com/container-platform/4.13/hardware_enablement/psap-node-feature-discovery-operator.html.

As of today the latest documentation version is 4.15.

The course should likely use a link https://docs.openshift.com/container-platform/latest/hardware_enablement/psap-node-feature-discovery-operator.html which yields a redirect to the latest published documentation version.

**Comment by adelton** [comment]
The information and the link is duplicated at https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/dependencies-install-web-console.html as well.

**Comment by adelton** [comment]
Similar issues at https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter2/users.html with [Adding roles to users](https://docs.openshift.com/container-platform/4.13/authentication/using-rbac.html#adding-roles_using-rbac) and at https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter2/resources.html with [Restrict resource consumption with limit ranges](https://docs.openshift.com/container-platform/4.14/nodes/clusters/nodes-cluster-limit-ranges.html).

**Comment by rsriniva** [comment]
fixed in main
