### ISSUE TITLE
redhat-cop links should likely be rendered differently

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-admin#50]
The page https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/dependencies-install-web-console.html has TIP rectangles

>  For assistance installing OpenShift Pipelines from YAML or via ArgoCD, refer to examples found in the \[redhat-cop/gitops-catalog/openshift-pipelines-operator](https://github.com/redhat-cop/gitops-catalog/tree/main/openshift-pipelines-operator) GitHub repo. 

>  For assistance installing the Node Feature Discovery Operator from YAML or via ArgoCD, refer to examples found in the \[redhat-cop/gitops-catalog/nfd](https://github.com/redhat-cop/gitops-catalog/tree/main/nfd) GitHub repo. 

>  For assistance installing the NVIDIA GPU Operator from YAML or via ArgoCD, refer to examples found in the \[redhat-cop/gitops-catalog/gpu-operator-certified](https://github.com/redhat-cop/gitops-catalog/tree/main/gpu-operator-certified) GitHub repo. 

where the markup is shown, instead of the link being rendered to the shorter text.

**Comment by adelton** [comment]
Also at https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/rhods-install-web-console.html.

**Comment by rsriniva** [comment]
fixed in main
