### ISSUE TITLE
Course shows installation of OpenShift AI 2.6 when 2.8 is the latest release

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-admin#51]
Page https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/rhods-install-web-console.html shows the installation of the OpenShift AI operators and the screenshots show 2.6 being the latest version.

Based on https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.8/html/release_notes/index, OpenShift AI 2.8 was already released.

**Comment by adelton** [comment]
This is actually a symptom of much bigger issue. The product can and will evolve and if these courses are part of the https://start.learning.redhat.com/ offering, their review and update for new releases should be part of the general process, not a catch up that your team would play, or one-off fixes when someone notices something.

**Comment by rsriniva** [comment]
Noted. @sarveshpandit - when you QA'd, was version 2.8? or older?

**Comment by rsriniva** [comment]
@sarveshpandit - for next round of QA, can we update the screenshots to v2.8 please?

**Comment by rsriniva** [comment]
fixed in main. updated with screenshots for RHOAI 2.8
