### ISSUE TITLE
URL to OpenShift AI notebooks repository

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-admin#52]
The page https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter3/custom.html says

> The default OpenShift AI notebook images can be found in the [Default OpenShift AI notebooks](https://github.com/opendatahub-io/notebooks) repository.

pointing to https://github.com/opendatahub-io/notebooks.

This contradicts with the information at 

> https://redhatquickcourses.github.io/rhods-intro/rhods-intro/1.33/chapter3/section3.html

which points to https://github.com/red-hat-data-services/notebooks/ (repo forked from https://github.com/opendatahub-io/notebooks).

If the Red Hat OpenShift AI Administration course talks about OpenShift AI, link to the "downstream" https://github.com/red-hat-data-services/notebooks/ is probably more accurate.

**Comment by rsriniva** [comment]
fixed in main
