### ISSUE TITLE
Course does not explain why the user might want to build their images on quay.io/mmurakam/workbenches:fraud-detection-v1.0.1

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-admin#53]
Page https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter3/custom.html shows how to build a custom notebook image with

```
FROM quay.io/mmurakam/workbenches:fraud-detection-v1.0.1
```

It goes to say that

> Our Fraud Detection image is using quay.io/modh/cuda-notebooks:cuda-jupyter-tensorflow-ubi9-python-3.9-2023a-20230714-933b52f as the base image.

It is however not clear why the user should want to take this "random" quay.io/mmurakam/workbenches:fraud-detection-v1.0.1 image as their base image and not the quay.io/modh/cuda-notebooks:cuda-jupyter-tensorflow-ubi9-python-3.9-2023a-20230714-933b52f directly. 

Or better yet, not that eight months old image which per https://quay.io/repository/modh/cuda-notebooks/manifest/sha256:817564f48843d5d976746aa40bdbc6099aedafbbddad7555bb88194834bc8712?tab=vulnerabilities&fixable=true has two critical security issues, but some significantly newer image, with fewer or no CVEs.

**Comment by rsriniva** [comment]
@mamurak @jramcast - suggestions to address this issue?

**Comment by rsriniva** [comment]
I'll update the instructions to use the base image. However, I notice that even the latest image built 5 days ago in quay shows 11 high vulnerabilities!

**Comment by rsriniva** [comment]
fixed in main.Thank you for the suggestion @adelton
