### ISSUE TITLE
Missing install step in "Build Steps"

### ISSUE THREAD

**Issue by viniciusfcf** [RedHatQuickCourses/rhods-admin#55]
After the command ``` COPY requirements.txt ./``` you need to install the package using the follow command:

```
RUN echo "Installing softwares and packages" && \     
    pip install micropipenv && \
    micropipenv install && \
    rm -f ./requirements.txt
```
PR to update the Containerfile: https://github.com/RedHatQuickCourses/rhods-qc-apps/pull/26

**Comment by rsriniva** [comment]
Thank you for the PR Vinicius! closing this due to https://github.com/RedHatQuickCourses/rhods-qc-apps/pull/26 being merged
