### ISSUE TITLE
New RHOAI version lifecycle

### ISSUE THREAD

**Issue by mamurak** [RedHatQuickCourses/rhods-admin#61]
Starting with RHOAI version 2.8, the product lifecycle has been changed and extended, which affects the operator update channels, version release cycles, and support coverage. [Installing Red Hat OpenShift AI Using the Web Console](https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/rhods-install-web-console.html) and [Upgrading Red Hat OpenShift AI](https://redhatquickcourses.github.io/rhods-admin/rhods-admin/1.33/chapter1/upgrading-rhods.html) still refer to the old product lifecycle and should be updated.

A short section should be added that summarizes the product lifecycle in terms of operator update channels and support coverage and refers to the [official product documentation](https://access.redhat.com/support/policy/updates/rhoai-sm/lifecycle) for details.

**Comment by kknoxrht** [comment]
updated the subscriptions screen capture showing the current options as of RHOAI 2.10.

https://github.com/RedHatQuickCourses/rhods-admin/pull/65
